;/////////////////////////////////////////////////////////
; resource.inc
; 类似于 VC 的 resource.h，用来定义所有需要用到的资源符号
;/////////////////////////////////////////////////////////
IFNDEF	_RESOURCE_INC_
_RESOURCE_INC_	equ	<1>

IDB_RENAME			equ  3
IDB_SCENE			equ  101
IDR_SFX_DIE			equ  107
IDR_SFX_HIT			equ  109
IDR_SFX_POINT		equ  110
IDR_SFX_SWOOSHING	equ  112
IDR_SFX_WING		equ  113
IDD_RANK			equ  114
IDD_RENAME			equ  116
IDB_CLEAR			equ  1001
IDC_NAME1			equ  1002
IDC_NAME2			equ  1003
IDC_NAME3			equ  1004
IDC_NAME4			equ  1005
IDC_NAME5			equ  1006
IDC_NAME6			equ  1007
IDC_NAME7			equ  1008
IDC_NAME8			equ  1009
IDC_NAME9			equ  1010
IDC_SCORE1			equ  1011
IDC_SCORE2			equ  1012
IDC_SCORE3			equ  1013
IDC_SCORE4			equ  1014
IDC_SCORE5			equ  1015
IDC_SCORE6			equ  1016
IDC_SCORE7			equ  1017
IDC_SCORE8			equ  1018
IDC_SCORE9			equ  1019
IDC_PLAYER_NAME		equ  1020

ENDIF