#include "stdafx.h"
#include "image_manager.h"

Spirit sp_dayBackground;
Spirit sp_nightBackground;
Spirit sp_ground;
Spirit sp_txtGetReady;
Spirit sp_txtGameOver;
Spirit sp_txtFlappyBird;
Spirit sp_txtCopyright;
Spirit sp_smallNum[10];
Spirit sp_middleNum[10];
Spirit sp_largeNum[10];
Spirit sp_scorePane;
Spirit sp_dliverMedal;
Spirit sp_goldenMedal;
Spirit sp_help;
Spirit sp_orangePipeUp;
Spirit sp_orangePipeDown;
Spirit sp_greenPipeUp;
Spirit sp_greenPipeDown;
Spirit sp_yellowBird[3];
Spirit sp_redBird[3];
Spirit sp_BlueBird[3];
Spirit sp_btPlay;
Spirit sp_btRank;
Spirit sp_btRate;
Spirit sp_btContinue;
Spirit sp_btPause;
Spirit sp_btShare;
Spirit sp_btMenu;
Spirit sp_btOk;